services:
  frontend:
    build:
      context: ./Work/lemon-frontend-main  # Path to the frontend directory
      dockerfile: Dockerfile               # Dockerfile inside the frontend folder
    ports:
      - "5173:5173"  # Maps local port 5173 to container port 5173 for frontend (Vite default)
    depends_on:
      - backend
    networks:
      - app-network
    environment:
      - VITE_API_URL=http://backend:8000  # Set the correct API URL for frontend (backend:8000)
    restart: always
  backend:
    build:
      context: ./Work/backend/empmanagebackend-main/empmanage  # Path to the backend Dockerfile
      dockerfile: Dockerfile                     # Dockerfile inside the empmanage folder
    ports:
      - "8000:8000"  # Maps local port 8000 to container port 8000 for backend
    depends_on:
      - database
    environment:
      - DATABASE_URL=mysql://root:Aryan@1234@database:3306/employeemanage  # Corrected DB connection URL
    networks:
      - app-network
    restart: always  # Ensures the backend container restarts if it fails

  database:
    image: mysql:8.0  # Use a stable MySQL image version
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword  # Set root password for MySQL
      MYSQL_USER: user                   # MySQL user
      MYSQL_PASSWORD: password           # MySQL user's password
      MYSQL_DATABASE: employeemanage  # Database to create on initialization
    volumes:
      - db_data:/var/lib/mysql  # Persist MySQL data
      # Uncomment the next line if you have a custom init.sql script
      # - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "3306:3306"  # Maps MySQL port 3306 to the host
    networks:
      - app-network
    restart: always  # Ensures the database container restarts if it fails

volumes:
  db_data:  # Volume to persist database data across container restarts

networks:
  app-network:
    driver: bridge  # En