# Generated by Django 5.1.1 on 2024-10-10 06:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("empapp", "0002_alter_employee_employee_id_alter_expense_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employee",
            name="employee_id",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="expense",
            name="date",
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name="timesheet",
            name="work_date",
            field=models.DateField(),
        ),
    ]
