# Generated by Django 5.1.1 on 2024-10-10 06:54

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("empapp", "0003_alter_employee_employee_id_alter_expense_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employee",
            name="employee_id",
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
