# Generated by Django 5.1.1 on 2024-10-10 07:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("empapp", "0004_alter_employee_employee_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employee",
            name="employee_id",
            field=models.CharField(max_length=100),
        ),
    ]
